SELECT * FROM PRODUTO_COMPRA
INNER JOIN PRODUTO_UNID ON (PRODUTO_COMPRA.cod_produto_fk = PRODUTO_UNID.codigo)
INNER JOIN PRODUTO_MARCA ON (PRODUTO_UNID.marca_fk = PRODUTO_MARCA.codigo)
INNER JOIN SUPERMERCADO ON (PRODUTO_COMPRA.mercado_compra_fk = SUPERMERCADO.codigo)
INNER JOIN USUARIO ON (PRODUTO_COMPRA.usuario_id_fk = USUARIO.id_usuario)
INNER JOIN ENDERECO ON (USUARIO.endereco_id_fk = ENDERECO.id_endereco)
INNER JOIN PRODUTO_ESTOQUE ON (PRODUTO_COMPRA.cod_produto_fk = PRODUTO_ESTOQUE.cod_produto_fk)
ORDER BY PRODUTO_COMPRA.cod_produto_fk ASC;